export interface BlogPost {
    slug: string;
    title: string;
    titleRo: string;
    date: string;
    author: string;
    category: string;
    categoryRo: string;
    excerpt: string;
    excerptRo: string;
}

export const blogPosts: BlogPost[] = [
    {
        slug: 'the-high-risk-ai-systems-under-the-ai-act-part-2',
        title: 'The High-Risk AI Systems under the AI Act (Part II): Biometrics and Critical Infrastructure',
        titleRo: 'Sistemele AI cu risc ridicat sub AI Act (Partea II): Biometrice și infrastructură critică',
        date: '2026-05-14',
        author: 'Matei Ștefan',
        category: 'AI Governance',
        categoryRo: 'Guvernanță AI',
        excerpt: 'The first two Annex III categories: biometric identification, categorisation and emotion-recognition systems — drawn carefully against the Article 5 prohibitions — and AI safety components in critical infrastructure (digital, road traffic, water, gas, heating, electricity).',
        excerptRo: 'Primele două categorii din Anexa III: sistemele de identificare biometrică, categorizare și recunoaștere a emoțiilor — trasate cu atenție în raport cu interdicțiile Articolului 5 — și componentele AI de siguranță în infrastructura critică (digitală, trafic rutier, apă, gaz, încălzire, electricitate).',
    },
    {
        slug: 'the-ai-omnibus-deal-what-was-agreed',
        title: 'The AI Omnibus Deal: What Was Agreed in the Trilogue',
        titleRo: 'Acordul AI Omnibus: Ce s-a convenit în trialog',
        date: '2026-05-09',
        author: 'Matei Ștefan',
        category: 'AI Governance',
        categoryRo: 'Guvernanță AI',
        excerpt: 'A provisional political agreement on AI regulation was reached on 7 May 2026, postponing high-risk compliance obligations by 16 months while introducing new protections against synthetic abuse imagery and clarifying overlaps with sectoral safety regimes.',
        excerptRo: 'Un acord politic provizoriu privind reglementarea AI a fost atins pe 7 mai 2026, amânând obligațiile de conformitate cu risc ridicat cu 16 luni, în timp ce introduce noi protecții împotriva imaginilor sintetice de abuz și clarifică suprapunerile cu regimurile sectoriale de siguranță.',
    },
    {
        slug: 'the-high-risk-ai-systems-under-the-ai-act-part-1',
        title: 'The High-Risk AI Systems under the AI Act (Part I): The Classification Framework and Annex I',
        titleRo: 'Sistemele AI cu risc ridicat sub AI Act (Partea I): Cadrul de clasificare și Anexa I',
        date: '2026-05-06',
        author: 'Matei Ștefan',
        category: 'AI Governance',
        categoryRo: 'Guvernanță AI',
        excerpt: 'How AI systems become classified as high-risk under the EU AI Act. The opening article walks through the two routes under Article 6 — the Annex I product-safety route and the Annex III use-case route — plus the Article 6(3) filter and substantial-modification rule.',
        excerptRo: 'Cum devin sistemele AI clasificate ca risc ridicat sub EU AI Act. Articolul de deschidere parcurge cele două rute sub Articolul 6 — ruta de siguranță a produselor din Anexa I și ruta cazurilor de utilizare din Anexa III — plus filtrul Articolului 6(3) și regula modificării substanțiale.',
    },
    {
        slug: 'how-ai-agents-are-regulated-under-eu-law',
        title: 'How AI Agents are Regulated Under EU Law',
        titleRo: 'Cum sunt reglementați agenții AI sub dreptul UE',
        date: '2026-05-02',
        author: 'Matei Ștefan',
        category: 'AI Governance',
        categoryRo: 'Guvernanță AI',
        excerpt: 'How the EU AI Act applies to autonomous AI agents, and where its static, intended-purpose risk framework strains under multi-step, tool-using systems. Three pillars come under particular pressure: human oversight, transparency, and traceability.',
        excerptRo: 'Cum se aplică EU AI Act agenților AI autonomi și unde cadrul său static, bazat pe scopul intenționat, este pus la încercare de sistemele multi-pas care folosesc unelte. Trei piloni sunt sub presiune specială: supravegherea umană, transparența și trasabilitatea.',
    },
    {
        slug: 'the-state-of-the-ai-omnibus-negotiations',
        title: 'The state of the “AI Omnibus” negotiations before heading into the trilogues',
        titleRo: 'Stadiul negocierilor „AI Omnibus” înainte de intrarea în trialoguri',
        date: '2026-04-12',
        author: 'Matei Ștefan',
        category: 'AI Governance',
        categoryRo: 'Guvernanță AI',
        excerpt: 'As EU institutions prepare for trilogue negotiations on the AI Act revisions, significant divergences emerge across prohibited practices, compliance timelines, and regulatory oversight. The Commission favors implementation flexibility, while both the Council and Parliament push for stricter requirements and fixed deadlines.',
        excerptRo: 'Pe măsură ce instituțiile UE se pregătesc pentru negocierile din trialoguri pe revizuirile AI Act, apar divergențe semnificative privind practicile interzise, calendarele de conformitate și supravegherea regulatorie. Comisia favorizează flexibilitatea de implementare, în timp ce atât Consiliul, cât și Parlamentul împing pentru cerințe mai stricte și termene fixe.',
    },
    {
        slug: 'the-prohibited-practices-under-the-ai-act-part-4',
        title: 'The Prohibited Practices under the AI Act (Part IV): Biometric Categorisation of Sensitive Traits and Real-Time Biometric Identification for Law Enforcement',
        titleRo: 'Practicile interzise sub AI Act (Partea IV): Categorizarea biometrică a trăsăturilor sensibile și identificarea biometrică în timp real pentru aplicarea legii',
        date: '2026-03-29',
        author: 'Matei Ștefan',
        category: 'AI Governance',
        categoryRo: 'Guvernanță AI',
        excerpt: 'The final installment in the series: biometric categorisation systems based on sensitive characteristics, and real-time remote biometric identification deployed in public spaces by law enforcement — two prohibitions operating at different stages of the AI lifecycle.',
        excerptRo: 'Ultimul articol din serie: sistemele de categorizare biometrică bazate pe caracteristici sensibile și identificarea biometrică la distanță în timp real implementată în spații publice de către forțele de aplicare a legii — două interdicții care operează la etape diferite ale ciclului de viață AI.',
    },
    {
        slug: 'the-prohibited-practices-under-the-ai-act-part-3',
        title: 'The Prohibited Practices under the AI Act (Part 3): Untargeted Scraping of Facial Images and Emotion Recognition',
        titleRo: 'Practicile interzise sub AI Act (Partea 3): Colectarea neorientată a imaginilor faciale și recunoașterea emoțiilor',
        date: '2026-03-28',
        author: 'Matei Ștefan',
        category: 'AI Governance',
        categoryRo: 'Guvernanță AI',
        excerpt: 'Two more prohibited practices under Article 5: the large-scale scraping of facial images to build biometric databases, and the use of emotion recognition systems in workplaces and educational institutions.',
        excerptRo: 'Încă două practici interzise sub Articolul 5: colectarea la scară largă a imaginilor faciale pentru construirea de baze de date biometrice și utilizarea sistemelor de recunoaștere a emoțiilor în locuri de muncă și instituții educaționale.',
    },
    {
        slug: 'the-prohibited-practices-under-the-ai-act-part-2',
        title: 'The Prohibited Practices under the AI Act (Part 2): Social Scoring and Predictive Policing',
        titleRo: 'Practicile interzise sub AI Act (Partea 2): Scoring social și poliție predictivă',
        date: '2026-03-17',
        author: 'Matei Ștefan',
        category: 'AI Governance',
        categoryRo: 'Guvernanță AI',
        excerpt: 'The AI Act bans social scoring systems that produce detrimental treatment across contexts and predictive policing based on profiling — while carving out lawful exceptions for credit assessments, fraud detection, and location-based crime analytics.',
        excerptRo: 'AI Act interzice sistemele de scoring social care produc tratament defavorabil între contexte și poliția predictivă bazată pe profilare — menținând excepții legale pentru evaluări de credit, detectarea fraudei și analitice de criminalitate bazate pe locație.',
    },
    {
        slug: 'the-prohibited-practices-under-the-ai-act',
        title: 'The Prohibited Practices under the AI Act (Part 1): Harmful Manipulation and Vulnerability Exploitation',
        titleRo: 'Practicile interzise sub AI Act (Partea 1): Manipularea dăunătoare și exploatarea vulnerabilităților',
        date: '2026-03-14',
        author: 'Matei Ștefan',
        category: 'AI Governance',
        categoryRo: 'Guvernanță AI',
        excerpt: 'At the apex of the AI Act\'s risk hierarchy sit the prohibited practices. This first of a four-part series examines harmful manipulation and vulnerability exploitation — the design red lines every AI product team must understand.',
        excerptRo: 'În vârful ierarhiei de risc a AI Act se află practicile interzise. Primul dintr-o serie de patru articole examinează manipularea dăunătoare și exploatarea vulnerabilităților — liniile roșii de design pe care orice echipă de produs AI trebuie să le înțeleagă.',
    },
    {
        slug: 'ai-as-a-regulated-product',
        title: 'AI as a Regulated Product: How the AI Act and the Product Liability Directive Work Together',
        titleRo: 'AI ca produs reglementat: Cum funcționează împreună AI Act și Directiva privind Răspunderea pentru Produse',
        date: '2026-03-09',
        author: 'Matei Ștefan',
        category: 'AI Governance',
        categoryRo: 'Guvernanță AI',
        excerpt: 'The EU has built a dual regulatory architecture for AI: the AI Act establishes ex ante product safety obligations, while the revised Product Liability Directive governs post-harm responsibility. Understanding both is essential for founders, CTOs, and product teams.',
        excerptRo: 'UE a construit o arhitectură regulatorie duală pentru AI: AI Act stabilește obligații de siguranță ex ante, iar Directiva revizuită privind Răspunderea pentru Produse guvernează responsabilitatea post-prejudiciu. Înțelegerea ambelor este esențială pentru fondatori, CTO-uri și echipele de produs.',
    },
    {
        slug: 'a-concise-yet-panoramic-introduction',
        title: 'A Concise Yet Panoramic Introduction to the EU AI Act',
        titleRo: 'O introducere concisă dar panoramică în EU AI Act',
        date: '2026-03-07',
        author: 'Matei Ștefan',
        category: 'AI Governance',
        categoryRo: 'Guvernanță AI',
        excerpt: 'A high-level overview of the EU AI Act: its legislative path, risk-based architecture, key actors, GPAI obligations, enforcement structure, and the emerging challenge of agentic AI systems.',
        excerptRo: 'O prezentare generală a EU AI Act: traseul legislativ, arhitectura bazată pe risc, actorii cheie, obligațiile GPAI, structura de aplicare și provocarea emergentă a sistemelor AI agentice.',
    },
    {
        slug: 'a-new-reality-in-ai-governance',
        title: 'The New Normal in AI Governance: Adjusting to life under the EU AI Act',
        titleRo: 'Noua normalitate \u00EEn guvernan\u021Ba AI: Adaptarea la via\u021Ba sub EU AI Act',
        date: '2026-03-01',
        author: 'Matei \u0218tefan',
        category: 'AI Governance',
        categoryRo: 'Guvernan\u021Ba AI',
        excerpt: 'Launching a blog series to dissect the complexities of the EU AI Act and translate them into actionable business intelligence and practical guidance.',
        excerptRo: 'Lans\u0103m o serie de articole pentru a analiza complexit\u0103\u021Bile EU AI Act \u0219i a le traduce \u00EEn informa\u021Bii de business ac\u021Bionabile \u0219i ghidare practic\u0103.',
    },
];
